package com.huawei.mops.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    private Long id;
    private String loginName;//用户名（域账号）
    private String userName; //用户名 (显示名)
    private String csicIds;//用户CSIC运维区域
    private String ccsIds;//用户CCS运维区域
    private String csic_father_Ids;//用户CSIC运维区域/父区域，用于主页 分域：区域/代表处节点访问页面时，优先展示用户运维节点的父节点
    private String passWord;//密码
    private String roleName;//角色名称
    private Integer regionId;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String loginName, String userName, String csicIds, String ccsIds, String csic_father_Ids, String passWord, String roleName, Integer regionId) {
        this.id = id;
        this.loginName = loginName;
        this.userName = userName;
        this.csicIds = csicIds;
        this.ccsIds = ccsIds;
        this.csic_father_Ids = csic_father_Ids;
        this.passWord = passWord;
        this.roleName = roleName;
        this.regionId = regionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getCsicIds() {
        return csicIds;
    }

    public void setCsicIds(String csicIds) {
        this.csicIds = csicIds;
    }

    public String getCcsIds() {
        return ccsIds;
    }

    public void setCcsIds(String ccsIds) {
        this.ccsIds = ccsIds;
    }

    public String getCsic_father_Ids() {
        return csic_father_Ids;
    }

    public void setCsic_father_Ids(String csic_father_Ids) {
        this.csic_father_Ids = csic_father_Ids;
    }

    public String getPassWord() {
        return passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Integer getRegionId() {
        return regionId;
    }

    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

}
